# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fundall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fundall
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'Alamofire', '~> 5.4'
  pod 'Toast-Swift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'

  target 'FundallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FundallUITests' do
    # Pods for testing
  end

end
